# Generated by Django 4.2 on 2024-06-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("number_in_stack", models.PositiveSmallIntegerField(default=0)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("C", "Crim"),
                            ("F", "Non Function"),
                            ("O", "Other"),
                            ("S", "Sci Fi"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="filter.author"
                    ),
                ),
            ],
        ),
    ]
